const { Router } = require('express')
const controllers = require('../controllers')
const router = Router()

router.get('/', (req, res) => res.send('This is root!'))
router.get('/recipes', controllers.getAllRecipes)
router.post('/recipes', controllers.createRecipe)
router.get('/recipes/:id', controllers.getRecipeById)
router.put('/recipes/:id', controllers.updateRecipe)
router.get('/cuisines', controllers.getAllCuisines)
router.get('/ingredients', controllers.getAllIngredients)
router.put('/cuisines/:id', controllers.updateCuisine)
router.put('/ingredients/:id', controllers.updateIngredient)
router.get('/cuisine/:name', controllers.getCuisineByName)
router.get('/ingredient/:name', controllers.getIngredByName)
router.delete('/recipes/:id', controllers.deleteRecipe)
router.get('/search', controllers.search)
router.get('/search/recipes', controllers.listRecipes)
router.get('/search/cuisines', controllers.cuisineSearch)
router.get('/search/ingredients', controllers.ingredSearch)

module.exports = router
